### ISSUE TITLE
Awesome script ---> add Spanish please

### ISSUE THREAD

**Issue by inglesuniversal** [MilosPaunovic/random-words#14]
it would be great for my students

regards

**Comment by MilosPaunovic** [comment]
Hi, will make it happen in the next few days.

**Comment by MilosPaunovic** [comment]
@inglesuniversal Added Spanish and published version 1.2.0 which includes it.

**Comment by inglesuniversal** [comment]
No kiddin' .... wow! I'm puzzled!!!

Let's try it!!!
