### ISSUE TITLE
Feature Request: allow user or developer to pre-select the level or complexity of the words

### ISSUE THREAD

**Issue by inglesuniversal** [MilosPaunovic/random-words#19]
I love your script, the issue I have is this... 

I am an English as a Second Language Teacher and the words your script generates are very uncommon in usage for my students.

Can you have a feature that either for English and Spanish, the script can generate the random words, but at the same time, allow the developer or end user to select the level or complexity of the words?

Example:

LEVEL 1

blue, banana, crayon, book, computer

LEVEL 2

understand, excited, shy, temper

LEVEL 3

acquire, uncertain, robust, reveal, attain, unabridged

... and the same for Spanish or any other Language

Hope you like this idea.

Hugo Barbosa

**Comment by MilosPaunovic** [comment]
Hi @inglesuniversal,

Seems like a reasonable request, but also one that would be very tricky to satisfy. The complexity of the words is pretty subjective and can't really be determined with absolute certainty.

What I could offer you is a way to choose length of the words, as shorter ones are (usually) less complex than longer ones.
To have something in the lines:

```js
const SIMPLE = RANDOM.words(howMany = 10, maxLength = 6)
```

How does that sound?

**Comment by inglesuniversal** [comment]
I'll give it a try and see what results and types of words it shows. Thanks and I will keep you posted.

**Comment by MilosPaunovic** [comment]
@inglesuniversal It's not yet implemented, it's just an idea at this point, but you could give it a test using something like this:

```js
const SIMPLE = RANDOM.words(1000).filter(w => w.length <= 5)
```

And see what you come up with.
