### ISSUE TITLE
TypeScript bug

### ISSUE THREAD

**Issue by romancitodev** [MilosPaunovic/random-words#20]
**Describe the bug**
when i import initialize from @paunovic/random-words could not find a declaration type, so its give me a error of 'any' type.
i tried to install @types/paunovic__random-words but the error continues.

**To Reproduce**
1. `import { initialize } from '@paunovic/random-words'`

**Screenshots**
![image](https://user-images.githubusercontent.com/84428770/174452107-f345be23-47c1-47c2-87cb-558b7cf4b109.png)

**Comment by MilosPaunovic** [comment]
Hi @ChirujanoCodding,

That's because the library wasn't written in `TypeScript`, but in plain `Javascript`. Maybe it will be re-written in the future, but, at this point, types aren't available.
